### PR TITLE
Improved readability table of content in sidabar

### PR DESCRIPTION
**Pull request by sun4sun**
About block "Table of Content"
- now it fixed position
- variable wide for menu items
- more readable text without wrapping

### CODE REVIEW

**Comment by stevepiercy** [comment]
Thanks for the submission, but it causes more problems than it solves:
- horizontal scrolling required to view the navigation items
- when there are many headings to view in the navlist such that it extends beyond the window height, the items below the frame are not viewable

Additionally, it is a higher priority to develop a Sphinx theme with a responsive layout for all Pylons Project projects, using http://trypyramid.com/ and one of the new Sphinx themes:
- https://github.com/snide/sphinx_rtd_theme
- https://github.com/bitprophet/alabaster
- https://github.com/ryan-roemer/sphinx-bootstrap-theme

The new layout will replace the Pyramid theme.

**Comment by blaflamme** [comment]
Work for a new theme has already started here, https://github.com/Pylons/pyramid-sphinx-themes and I'm not satisfied with most theme, responsive or not, out there. I'm thinking about waiting for BS4 being done, or possibly go with semantic-ui.com.

**Comment by stevepiercy** [comment]
I forgot to mention, we also made a long list of notes of the existing state of our themes and what we would consider and change in [New Theme Requests](https://github.com/Pylons/pylons_sphinx_theme/wiki/New-Theme-Requests).

**Comment by pauleveritt** [comment]
My two cents: Blaise, we should try to live without BS 4 and any minor complaints, and just get something rolled out. The “new theme” effort has been the key to a number of things over the years. We need to get something in place, out the door, and refine later.

—Paul

**Comment by stevepiercy** [comment]
@blaflamme @pauleveritt I'm very much in favor of using what is available now and not waiting for the next thing. I have a lot of free time now to work on this stuff, too.

**Pull request closed without merging**
