### PR TITLE
Revamp pyramid doc style

### PR DESCRIPTION
**Pull request by jumapico**
Improve the documentation style using the same new style as trypyramid.com.
The pyramid.css file is pylons.css from the pylons theme modified with minor changes in the colors.

The styles for *notes* and *seealso* (examples in <https://docs.pylonsproject.org/projects/pyramid/en/master/quick_tutorial/requirements.html>) are unchanged and maybe also need changes.

### CODE REVIEW

**Comment by stevepiercy** [comment]
@jumapico please see the discussion in #1. I don't want to spend time with minor tweaks to the styles of existing themes because they don't solve the issues we need to solve. We need a complete overhaul.

For building a demo of all the things that might appear in docs, I would suggest using https://github.com/Pylons/docs-style-guide

Perhaps this would be a good sprint topic at [PloneConf](https://ploneconf.org).

**Comment by jumapico** [comment]
Thanks for your fast response @stevepiercy.
I go to look at [docs-style-guide](https://github.com/Pylons/docs-style-guide).
Regards,
JMPC

**Comment by blaflamme** [comment]
@stevepiercy don't you think it could be a good improvement till we have the new theme done? I mean actually the old brand is more branded than the new one since the current doc theme is used by multiple projects, not only ours. It could, at least, help dropping the old brand.

**Comment by stevepiercy** [comment]
@blaflamme you are welcome to work on tweaks. I personally don't want to distract myself from the long-term plan for both Pylons Project and Pyramid themes.

**Pull request closed without merging**
